version: '3.9'

services:
  db: # database service
    container_name: polarexpress-db
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    profiles: [prod, dev]
  
  backend-base: # base service for backend, do not run! 
    build: 
      context: .
      dockerfile: Dockerfile
    profiles: [never]

  backend-prod: 
    container_name: polarexpress-backend
    extends:
      service: backend-base
    build:
      target: prod
    depends_on:
      - db
    profiles: [prod]     

  backend-dev:
    container_name: polarexpress-backend-dev
    extends:
      service: backend-base
    build:
      target: dev
    depends_on:
      - db
    profiles: [dev]

volumes:
  db-data:
