version: "3.9"

services:
  backend:
    container_name: gp-marketplace-backend
    extends:
      file: docker-compose.base.yml
      service: backend-base

volumes:
  db-data:
    name: gp-marketplace-db-data
