version: '3.9'

services:
  db: # database service
    container_name: gp-marketplace-db
    extends:
      file: docker-compose.base.yml
      service: db
    profiles: [prod, dev]

  backend-prod: 
    container_name: gp-marketplace-backend
    extends:
      file: docker-compose.base.yml
      service: backend-base
    build:
      target: prod
    depends_on:
      - db
    profiles: [prod]     

  backend-dev:
    container_name: gp-marketplace-backend
    extends:
      file: docker-compose.base.yml
      service: backend-base
    build:
      target: dev
    depends_on:
      - db
    profiles: [dev]
  
  backend-testing:
    container_name: gp-marketplace-backend-testing
    extends:
      file: docker-compose.base.yml
      service: backend-base
    build:
      target: testing
    profiles: [test]

volumes:
  db-data:
    name: gp-marketplace-db-data