name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  jest:
    name: Jest (unit tests)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Jest
        run: npm run test

  eslint:
    name: ESLint (linting)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run linter
        run: npm run lint

  prettier:
    name: Prettier (formatting)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Prettier
        run: npm run format
  # build-docker-prod:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build Dockerfile
  #     run: docker buildx build --target prod -t backend-test-image .
