name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened", "ready_for_review"]
    branches: ["main"]

jobs:
  jest:
    name: Jest (unit tests)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Jest
        run: pnpm test

      - name: Report test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0

  build:
    name: tsc (build)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Build project
        run: pnpm build

  eslint:
    name: ESLint (linting)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run linter
        run: pnpm lint

  prettier:
    name: Prettier (formatting)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Prettier
        run: npx prettier --check .
