name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened", "ready_for_review"]
    branches: ["main"]

jobs:
  jest:
    name: Jest (unit tests)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: check

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: PolarExpress/ts-configs/.github/actions/ci-env@main

      - name: Run Jest
        run: pnpm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage/lcov-report
          retention-days: 30
          if-no-files-found: error # this should never fail!

  check:
    uses: PolarExpress/ts-configs/.github/workflows/ci-workflow.yml@main
