name: CI

on:
  pull_request:
    types: ["opened", "synchronize", "reopened", "ready_for_review"]
    branches: ["main"]

permissions:
  pull-requests: write

jobs:
  jest:
    name: Jest (unit tests)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Jest
        run: npm run test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage/lcov-report
          retention-days: 30
          if-no-files-found: error # this should never fail!

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 85
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

  eslint:
    name: ESLint (linting)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run linter
        run: npm run lint

  prettier:
    name: Prettier (formatting)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Prettier
        run: npx prettier --check .
